omgnetwork/omg-js

package-lock.json
packages/omg-js-childchain/package.json
packages/omg-js-childchain/src/index.js
packages/omg-js-childchain/test/getBalanceTest.js
packages/omg-js/src/index.js

I realised that the version of the Watcher that implements `/account/${address}/balance` may not be available on our testnet any time soon, so I've changed the getBalance() code calculate the balance from utxos for now.

Implement getBalance() using getUtxos()

---

packages/integration-tests/test/challengeExitTest.js
packages/integration-tests/test/depositExitTest.js
packages/integration-tests/test/helper.js
packages/integration-tests/test/transferTest.js
packages/integration-tests/test/utxoExitTest.js
packages/omg-js-childchain/src/index.js
packages/omg-js-rootchain/src/index.js

Added RootChain.startDepositExit()
Export ChildChain.encodeUtxoPos()
Added some more handy test helper functions

Deposit exit

---

documentation.yml
examples/node-deposit.js
packages/omg-js-rootchain/src/index.js

Remove RootChain.getDepositBlock()

---

packages/omg-js-rootchain/src/index.js
packages/omg-js-rootchain/src/plasmaAbi.js

- removed fromAddress from the `depositFrom` plasma method 
- modified plasma default abi
fix: https://github.com/omisego/omg-js/issues/51

fixed depositFrom abi and method call

---

package-lock.json
package.json
packages/integration-tests/README.md
packages/integration-tests/test-config.js
packages/integration-tests/test/depositTest.js
packages/integration-tests/test/helper.js
packages/integration-tests/tokens/contracts/ERC20.sol
packages/integration-tests/tokens/contracts/Migrations.sol
packages/integration-tests/tokens/migrations/1_initial_migration.js
packages/integration-tests/tokens/migrations/2_deploy_contracts.js
packages/integration-tests/tokens/truffle.js
packages/omg-js-rootchain/src/index.js

We had no ERC20 tests, so I wanted to get one up. There is some manual setup required before running the test, but we can automate it later...

ERC20 deposit integration test

---

packages/omg-js-childchain/src/index.js
packages/omg-js-childchain/src/transaction/transaction.js
packages/omg-js-childchain/test/createTransactionBodyTest.js

ChildChain.sendTransaction() returns change

---

packages/omg-js-rootchain/src/index.js
packages/omg-js-util/src/transaction.js
packages/omg-js-util/test/decodeTransactionTest.js
packages/omg-js-util/test/validateTransactionTest.js

Fix transaction.decode() implementation and add tests

Decode transaction

---

packages/omg-js-rootchain/src/txUtils.js

fix https://github.com/omisego/omg-js/issues/115

added 0x prefix before signing

---

packages/integration-tests/helpers/rootChainHelper.js
packages/integration-tests/helpers/testFaucet.js
packages/integration-tests/test-config.js
packages/integration-tests/test/depositTest.js
packages/omg-js-childchain/package-lock.json
packages/omg-js-rootchain/src/contracts/Erc20Vault.json
packages/omg-js-rootchain/src/contracts/EthVault.json
packages/omg-js-rootchain/src/contracts/ExitGameRegistry.json
packages/omg-js-rootchain/src/contracts/PlasmaFramework.json
packages/omg-js-rootchain/src/rootchain.js
packages/omg-js-rootchain/src/txUtils.js
packages/omg-js-util/package-lock.json
packages/omg-js-util/package.json
packages/omg-js-util/src/transaction.js
packages/omg-js-util/src/transactionALD.js

my test config
```
const config = {
geth_url: process.env.GETH_URL || 'https://rinkeby.infura.io/v3/93e4060ae75143ccb90fc27b84864d7e',
watcher_url: process.env.WATCHER_URL || 'http://dev-a960a7b-watcher.omg.network/',
childchain_url: process.env.CHILDCHAIN_URL || 'http://dev-a960a7b-childchain.omg.network/',
rootchainContract: process.env.ROOTCHAIN_CONTRACT || '0x61b3ccfaa1e2fbe5cf073dff470695de788aca69',
contract_exchanger_url: process.env.CONTRACT_EXCHANGER_URL || 'http://localhost:5000/get_contract',
testErc20Contract: process.env.TEST_ERC20_CONTRACT || '0xc778417E063141139Fce010982780140Aa0cD5Ab',
fundAccount: process.env.FUND_ACCOUNT || '',
fundAccountPrivateKey: process.env.FUND_ACCOUNT_PRIVATEKEY || '',
fundAccountPassword: process.env.FUND_ACCOUNT_PASSWORD || '', …
```

Initialize new contracts & eth depoist & erc20 deposit

---

packages/integration-tests/test/addTokenTest.js
packages/omg-js-rootchain/src/rootchain.js

update addToken for ALD
with tests 🎉

AddToken (addexitqueue)

---

packages/integration-tests/helpers/testFaucet.js
packages/integration-tests/test/challengeExitTest.js
packages/integration-tests/test/inFlightExitChallengeResponse.js
packages/integration-tests/test/inFlightExitChallengeTest.js
packages/integration-tests/test/inFlightExitTest.js
packages/integration-tests/test/standardExitTest.js
packages/omg-js-rootchain/src/rootchain.js
packages/omg-js-util/src/ethErrorReason.js

- minor refactor for integration test
- integration test for piggybacking input

Piggy back input integration test

---

examples/childchain-exit-erc20.js
examples/childchain-exit-eth.js
examples/childchain-inflight-exit-eth.js
packages/omg-js-rootchain/package-lock.json
packages/omg-js-rootchain/package.json
packages/omg-js-rootchain/src/rootchain.js
packages/omg-js-rootchain/src/txUtils.js

[185](https://github.com/omisego/omg-js/issues/185)
[174](https://github.com/omisego/omg-js/issues/174)

174 get exit ids for process exits

---

README.md
docs/index.html
documentation.yml
examples/childchain-deposit-erc20.js
examples/childchain-deposit-eth.js
packages/integration-tests/helpers/childChainHelper.js
packages/integration-tests/helpers/rootChainHelper.js
packages/integration-tests/helpers/testFaucet.js
packages/integration-tests/package-lock.json
packages/integration-tests/package.json
packages/integration-tests/test/decodeTxBytesTest.js
packages/integration-tests/test/depositTest.js
packages/integration-tests/test/inFlightExitChallengeTest.js
packages/integration-tests/test/standardExitTest.js
packages/integration-tests/test/transferTest.js
packages/omg-js-rootchain/src/rootchain.js
packages/omg-js-rootchain/src/validators/index.js

do the encode in deposit, bit simpler api for the user
also removed some unused functions to start cleaning up cchelper and rchelper

Simplify deposit

---

docs/index.html
documentation.yml
examples/process-exits.js
packages/integration-tests/test/getExitQueueTest.js
packages/omg-js-rootchain/src/contracts/PriorityQueue.json
packages/omg-js-rootchain/src/rootchain.js

`rootchain.getExitQueue(<token = ETH>)` returns current exit queue for the passed token
[201](https://github.com/omisego/omg-js/issues/201)

Get current exit queue

---

docs/index.html
examples/childchain-deposit-erc20.js
examples/childchain-deposit-eth.js
packages/integration-tests/helpers/childChainHelper.js
packages/integration-tests/helpers/testFaucet.js
packages/integration-tests/test/decodeTxBytesTest.js
packages/integration-tests/test/depositTest.js
packages/integration-tests/test/getExitQueueTest.js
packages/integration-tests/test/standardExitTest.js
packages/omg-js-rootchain/src/rootchain.js
packages/omg-js-rootchain/src/validators/index.js
packages/omg-js-util/src/docTypes.js

[215](https://github.com/omisego/omg-js/issues/215)

Remove owner arg from deposit

---

examples/childchain-utxos.js
examples/package-lock.json
examples/package.json

because native stringify unable to parse bn
[218](https://github.com/omisego/omg-js/issues/218)

Readable utxos in examples

---

README.md

Thanks to @nicholasmueller for the support

Add ERC20 deployment instructions before ERC20 examples

---

README.md
docs/index.html
lerna.json
package.json
packages/integration-tests/package-lock.json
packages/integration-tests/package.json
packages/omg-js-childchain/package-lock.json
packages/omg-js-childchain/package.json
packages/omg-js-rootchain/package-lock.json
packages/omg-js-rootchain/package.json
packages/omg-js-util/package-lock.json
packages/omg-js-util/package.json
packages/omg-js/package-lock.json
packages/omg-js/package.json

fixes [dependency issue](https://github.com/omisego/omg-js/issues/238)

V3.0.0 alpha.21 release

---

package.json
packages/browser-omg-js/package.json
packages/omg-js-childchain/package.json
packages/omg-js-rootchain/package.json
packages/omg-js-util/package.json
packages/omg-js/package.json
packages/react-native-omg-js/package.json

https://github.com/omisego/omg-js/issues/272

Emails -> gh handles

---

.circleci/config.yml
package-lock.json
package.json

#276 
- fix package lock for minimalist package
note that we will still getting low vulnerability warning, this problem need to wait for other deps to be updated
- add circle ci check audit, if we have a moderate vulnerability, test failed

fix package json

---

packages/integration-tests/test/challengeExitTest.js
packages/integration-tests/test/standardExitTest.js

Add more gas to calls to processExits in case there are more exits in the queue

add more gas when calling processExits

---

.circleci/config.yml
docs/index.html
lerna.json
package-lock.json
package.json
packages/browser-omg-js/package-lock.json
packages/browser-omg-js/package.json
packages/integration-tests/package-lock.json
packages/integration-tests/package.json
packages/omg-js-childchain/package-lock.json
packages/omg-js-childchain/package.json
packages/omg-js-rootchain/package-lock.json
packages/omg-js-rootchain/package.json
packages/omg-js-util/package-lock.json
packages/omg-js-util/package.json
packages/omg-js/package-lock.json
packages/omg-js/package.json
packages/react-native-omg-js/package-lock.json
packages/react-native-omg-js/package.json

bump and run ci against 1.0.4 of elixir-omg

v4.1.0-1.0.4 release

---

examples/wait.js
packages/integration-tests/helpers/faucet.js
packages/omg-js-rootchain/src/rootchain.js

missed some eth_calls made internally, from is optional (but not if using infura) so we can be explicit

Handle infura API changes
